
"@context":

ontologies:

  - id: upheno2
    preferredPrefix: UPHENO
    title: Unified Phenotype Ontology (uPheno2)
    description: >
      Cross-species integrated phenotype ontology
    uri: https://ci.monarchinitiative.org/view/pipelines/job/upheno2/lastSuccessfulBuild/artifact/src/curation/upheno-release/all/upheno_all_with_relations.owl
    base_uri:
      - http://purl.obolibrary.org/obo/UPHENO_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
#    label_property:  http://www.w3.org/2004/02/skos/core#prefLabel
    reasoner: EL
    oboSlims: false
    ontology_purl : file:/opt/ols/ontologies/upheno2.owl
  - id: upheno_patterns
    preferredPrefix: UPHENO_PATTERN
    title: Unified Phenotype Ontology Pattern Ontology
    description: >
      Ontology that contains all the currently defined uPheno patterns
    uri: http://purl.obolibrary.org/obo/upheno/patterns/pattern.owl
    base_uri:
      - http://purl.obolibrary.org/obo/UPHENO_PATTERN_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
#    label_property:  http://www.w3.org/2004/02/skos/core#prefLabel
    reasoner: EL
    ontology_purl : file:/opt/ols/ontologies/upheno_patterns.owl
  - id: geno
    preferredPrefix: GENO
    uri: http://purl.obolibrary.org/obo/geno.owl
    base_uri:
      - http://purl.obolibrary.org/obo/GENO_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
#    label_property:  http://www.w3.org/2004/02/skos/core#prefLabel
    reasoner: EL
    oboSlims: false
    ontology_purl : file:/opt/ols/ontologies/geno.owl
  - id: hp
    preferredPrefix: HP
    title: Human Phenotype Ontology (Development Snapshot)
    uri: http://purl.obolibrary.org/obo/hp.owl
    description: >
      Inofficial development snapshot of the Human Phenotype Ontologies. Contact Peter Robinson.
    base_uri:
      - http://purl.obolibrary.org/obo/HP_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
#    label_property:  http://www.w3.org/2004/02/skos/core#prefLabel
    reasoner: EL
    oboSlims: false
    ontology_purl : file:/opt/ols/ontologies/hp.owl
  - id: chr
    preferredPrefix: CHR
    title: Monochrom Ontology (Development Snapshot)
    uri: https://raw.githubusercontent.com/monarch-initiative/monochrom/master/chr.owl
    description: >
      Inofficial development snapshot of the Human Phenotype Ontologies. https://github.com/monarch-initiative/monochrom/issues
    base_uri:
      - http://purl.obolibrary.org/obo/HP_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
#    label_property:  http://www.w3.org/2004/02/skos/core#prefLabel
    reasoner: EL
    oboSlims: false
    ontology_purl : file:/opt/ols/ontologies/chr.owl
    
#   - id: monarch
#     preferredPrefix: MO
#     title: Monarch Ontology (Development Snapshot)
#     uri: http://purl.obolibrary.org/obo/monarch.owl
#     description: >
#       Development snapshot of the Monarch Ontology, see: https://github.com/monarch-initiative/monarch-ontology.
#     base_uri:
#       - http://purl.obolibrary.org/obo/MO_
#     synonym_property:
#       - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
#     definition_property:
#       - http://purl.obolibrary.org/obo/IAO_0000115
# #    label_property:  http://www.w3.org/2004/02/skos/core#prefLabel
#     reasoner: EL
#     oboSlims: false
#     ontology_purl : file:/opt/ols/ontologies/monarch.owl
